/*
Script Generated By : Converter.py
Date                : 2023-11-27 17:40:00"
Description         : "Converted input.sql to redshift_output.sql"
*/
with rpt_dim_advisor_hierarchy as (
select 1 as advisor_hierarchy_seq_key_id, 1 as advisor_hierarchy_key_id, 1 as advisor_key_id, 1 as channel_key_id, 1 as firm_key_id, 1 as agency_key_id, 1 as sas_office_key_id, '' as src_advisor_key, '' as src_profile_key, 1 as ega_key, 1 as maga_key, 1 as asm_key, 1 as rsm_key, '' as src_ega_key, '' as src_maga_key, '' as src_asm_key, '' as src_rsm_key, '' as src_firm_key, '' as src_agency_key, '' as admin_cd, '' as management_level, date('01-01-1900') as src_eff_start_dt, date('01-01-1900') as src_eff_end_dt, '' as deleted_flg, '' as src_sys_name, date('01-01-1900') as eff_start_dt, date('01-01-1900') as eff_end_dt, 1 as active_ind, 1 as batch_num, date('01-01-1900') as load_dts, '' as lst_updt_usr, date('01-01-1900') as lst_updt_dts, 1 as crediting_address_key_id, 1 as crediting_address_type_key_id
),


select distinct
        rdc.sub_chnl_cd, rdc.dim_chnl_id, ppe.plcy_num as "policy #", ppe.prod_premium_amt,
        case
            when ppe.lob_cd = 'term' then ppe.prod_premium_amt
            when pr.prod_sub_grp_cd in ('mg') and pr.prod_cd in ('mma', 'mfa') then /*total_policy_val */
            when pr.prod_sub_grp_cd in ('mg') then ppe.rop_thrshld_amt
            when ppe.tgt_premium_amt = 0 then nvl(ppe.prod_premium_amt, 0)
            else nvl(ppe.tgt_premium_amt, nvl(ppe.prod_premium_amt, 0))
        end as target,
        case
            when pr.prod_sub_grp_cd in ('mg') and pr.prod_cd in ('mma', 'mfa') then /*total_policy_val */
            when pr.prod_sub_grp_cd in ('mg') then ppe.rop_thrshld_amt * 0.15
            else nvl(ppe.prod_premium_amt, 0)
        end as premium,
        case
            when ppe.applctn_typ_cd = 'tri' then 'trial'
            when pr.prod_sub_grp_cd in ('mg') then replace(pr.prod_typ_desc, 'moneyguard', 'mg')
            else ppe.lob_desc
        end as lob,
        case
            when rdc.sub_chnl_cd = 'lfa' or (df.firm_cdw_id = 'cdw002849' and rdc.dim_chnl_id in ('ipi', 'wrh', 'bnk', 'hyb')) then 'lfa'
        /* advisor */
            when rdc.sub_chnl_cd in ('pgrp', 'mgrp') then 'producer group'
        /* advisor */
            when rdc.sub_chnl_cd in ('wrh', 'bnk') then 'wire/bank'
        /* advisor */
            when rdc.sub_chnl_cd in ('edj') then 'ed jones'
        /* advisor */
            when rdc.sub_chnl_cd in ('mga') and pr.prod_typ_cd = 'tm' and rsm.advsr_full_nm like '%selectquote%' then 'select quote'
        /* aggregator */
            when rdc.sub_chnl_cd in ('ga') and rda.agcy_cdw_id in ('cdwe16995') and pr.prod_typ_cd = 'tm' then 'ga aggregator'
        /* aggregator */
            when rdc.sub_chnl_cd in ('ga') and rda.agcy_cdw_id in ('cdwe21155') and pr.prod_typ_cd = 'tm' then 'ga aggregator'
        /* aggregator */
            when rdc.sub_chnl_cd in ('una') then 'unassigned'
        /* when rdc.sub_chnl_cd in('lfa','ga aggregator','ga','abga') then 'lfn total' -- lfn */
            else rdc.sub_chnl_cd
            /* brokerage:(mga,abga,ga), lfn:(abga,ga,lfga) */
        end as "dist channel", f.dim_chnl_id, f.dim_plcy_id
        --into "#t2_life_lfn_pipeline_summary_procedure"
        from vikas_dummy.dim_plcy as ppe
        join vikas_dummy.fct_dly_plcy_trx as f
            on ppe.dim_plcy_id = f.dim_plcy_id
        join vikas_dummy.bridge channel subchannel relationship as rdc
            on f.dim_chnl_id = rdc.dim_chnl_id
        join vikas_dummy.dim_prod as pr
            on f.dim_prod_id = pr.dim_prod_id
        left outer join vikas_dummy.dim_plcy as psc
            on /*status_cd_key_id */ = /*status_cd_key_id */
        left outer join vikas_dummy.dim_plcy as rdp
            on ppe.dim_plcy_id = rdp.dim_plcy_id
        left outer join vikas_dummy.dim_firm as df
            on f.dim_firm_id = df.dim_firm_id
        left outer join vikas_dummy.dim_advsr_hierarchy as ah
            on /*advisor_hierarchy_key_id */ = ah.advisor_hierarchy_key_id
        left outer join vikas_dummy.dim_advsr as rsm
            on ah.rsm_key = rsm.advsr_mdm_id
        left outer join vikas_dummy.dim_agcy as rda
            on ah.agency_key_id = rda.agcy_mdm_id
        where ((psc.plcy_status_cd in ('pnd') or (psc.plcy_status_desc in ('trial closed') and null <= 90)) and f.is_compensbl_flg = 'y' and f.trx_grp_cd = 'p' and
        case
            when rdc.sub_chnl_cd = 'lfa' or (df.firm_cdw_id = 'cdw002849' and rdc.dim_chnl_id in ('ipi', 'wrh', 'bnk', 'hyb')) then 'lfa'
        /* advisor */
            when rdc.sub_chnl_cd in ('pgrp', 'mgrp') then 'producer group'
        /* advisor */
            when rdc.sub_chnl_cd in ('wrh', 'bnk') then 'wire/bank'
        /* advisor */
            when rdc.sub_chnl_cd in ('edj') then 'ed jones'
        /* advisor */
            when rdc.sub_chnl_cd in ('mga') and pr.prod_typ_cd = 'tm' and rsm.advsr_full_nm like '%selectquote%' then 'select quote'
        /* aggregator */
            when rdc.sub_chnl_cd in ('ga') and rda.agcy_cdw_id in ('cdwe16995') and pr.prod_typ_cd = 'tm' then 'zander'
        /* aggregator */
            when rdc.sub_chnl_cd in ('ga') and rda.agcy_cdw_id in ('cdwe21155') and pr.prod_typ_cd = 'tm' then 'policygenius'
        /* aggregator */
        /* when rdc.sub_chnl_cd in('lfa','ga aggregator','ga','abga') then 'lfn total' -- lfn */
            else rdc.sub_chnl_cd
            /* brokerage:(mga,abga,ga), lfn:(abga,ga,lfga) */
        end in ('lfa', 'ga', 'abga', 'zander', 'policygenius') and pr.prod_sub_grp_cd in ('life', 'mg') and ppe.plcy_num not in ('mg10056058', 'mg10062801'));
    --open cur for
    select
        case
            when "dist channel" in ('lfa', 'ga', 'ga aggregator', 'abga') then 'lfn total'
            else "dist channel"
        end as "dist channel", nvl(lob, '') as lob, sum(premium) as premium, count("policy #") as "policy count", sum(target) as target
        from "#t2_life_lfn_pipeline_summary_procedure"
        /* where [dist channel] in ('lfa','ga','ga aggregator','abga') */
        group by
        case
            when "dist channel" in ('lfa', 'ga', 'ga aggregator', 'abga') then 'lfn total'
            else "dist channel"
        end, nvl(lob, '')
    union
    select
        nvl("dist channel", '') as "dist channel", nvl(lob, '') as lob, sum(premium) as premium, count("policy #") as "policy count", sum(target) as target
        from "#t2_life_lfn_pipeline_summary_procedure"
        group by nvl("dist channel", ''), nvl(lob, '')
        order by 1 desc nulls first;

